<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'wikimedia\\es\\entity' => '/Entity.php',
                'wikimedia\\es\\entityid' => '/EntityId.php',
                'wikimedia\\es\\entitymade' => '/EntityMade.php',
                'wikimedia\\es\\event' => '/Event.php',
                'wikimedia\\es\\snak' => '/Snak.php',
                'wikimedia\\es\\statement' => '/Statement.php',
                'wikimedia\\es\\statementid' => '/StatementId.php',
                'wikimedia\\es\\statementmade' => '/StatementMade.php',
                'wikimedia\\es\\statementpublished' => '/StatementPublished.php',
                'wikimedia\\es\\statementrankupdated' => '/StatementRankUpdated.php',
                'wikimedia\\es\\statementrankupdatedeventhandler' => '/StatementRankUpdatedEventHandler.php',
                'wikimedia\\es\\statementrejected' => '/StatementRejected.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
