<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'wikimedia\\es\\statement' => '/Statement.php',
                'wikimedia\\es\\statementaccepted' => '/StatementAccepted.php',
                'wikimedia\\es\\statementacceptedeventhandler' => '/StatementAcceptedEventHandler.php',
                'wikimedia\\es\\statementid' => '/StatementId.php',
                'wikimedia\\es\\statementmade' => '/StatementMade.php',
                'wikimedia\\es\\statementpublished' => '/StatementPublished.php',
                'wikimedia\\es\\statementrejected' => '/StatementRejected.php',
                'wikimedia\\es\\event' => '/Event.php',
                'wikimedia\\es\\snak' => '/Snak.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
